---
- name: Install Consul on nomad-server
  hosts: nomad-server
  vars:
    - consul_server_ip: "{{ hostvars['nomad-server']['ansible_default_ipv4']['address'] }}"
  become: yes
  roles:
   - consul-server

- name: Install Consul on consul-client-one
  hosts: consul-client-one
  vars:
    - consul_server_ip: "{{ hostvars['nomad-server']['ansible_default_ipv4']['address'] }}"
    - consul_client_ip: "{{ hostvars['consul-client-one']['ansible_default_ipv4']['address'] }}"
  become: yes
  roles:
   - consul-client

- name: Install Consul on consul-client-two
  hosts: consul-client-two
  vars:
    - consul_server_ip: "{{ hostvars['nomad-server']['ansible_default_ipv4']['address'] }}"
    - consul_client_ip: "{{ hostvars['consul-client-two']['ansible_default_ipv4']['address'] }}"
  become: yes
  roles:
   - consul-client

- name: Install Nomad on nomad-server
  hosts: on nomad-server
  vars:
    - nomad_server_ip: "{{ hostvars['nomad-server']['ansible_default_ipv4']['address'] }}"
    - consul_server_ip: "{{ hostvars['nomad-server']['ansible_default_ipv4']['address'] }}"
  become: yes
  roles:
   - nomad-server