---

- name: Get Consul binary archieve
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp/consul_{{ consul_version }}_linux_amd64.zip
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 3
  check_mode: false

- name: Unpack Consul binary
  unarchive:
    src: /tmp//consul_{{ consul_version }}_linux_amd64.zip
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/consul"
    remote_src: yes
  check_mode: false

- name: Create needed folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /var/consul
    - /etc/consul.d/client

- name: Template a client_config
  template:
    src: client_config.json.j2
    dest: /etc/consul.d/client/config.json

- name: Template a consul.service
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
  notify:
    - Restart Consul
