---
- name: Get Nomad binary archieve
  get_url:
    url: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip
    dest: /tmp//nomad_{{ nomad_version }}_linux_amd64.zip
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 3
  check_mode: false

- name: Unpack nomad binary
  unarchive:
    src: /tmp/nomad_{{ nomad_version }}_linux_amd64.zip
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/nomad"
    remote_src: yes
  check_mode: false

- name: Create needed folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/nomad.d
    - /opt/nomad

- name: Template a nomad.hcl
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: Template a server.hcl
  template:
    src: server.hcl.j2
    dest: /etc/nomad.d/server.hcl

- name: Template a nomad.service
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
  notify:
    - Restart Nomad

- name: Create Nomad jobs directory
  file:
    path: /home/vagrant/nomad_jobs
    state: directory
    mode: '0755'
    owner: vagrant
    group: vagrant

- name: Create demo job file
  file:
    path: /home/vagrant/nomad_jobs/example.nomad
    state: touch
    mode: '0644'
    owner: vagrant
    group: vagrant

- name: Insert demo job content
  blockinfile:
    block: "{{ lookup('file', '../templates/example_job.j2') }}"
    path: /home/vagrant/nomad_jobs/example.nomad
    owner: vagrant
    group: vagrant

- name: Pause for Nomad service
  pause:
    minutes: 3

- name: Plan demo job 
  shell: "nomad job plan -address=http://{{ nomad_server_ip }}:4646 example.nomad"
  args:
    chdir: /home/vagrant/nomad_jobs
  become_user: vagrant
  ignore_errors: true

- name: Run demo job
  shell: "nomad job run -address=http://{{ nomad_server_ip }}:4646 example.nomad"
  args:
    chdir: /home/vagrant/nomad_jobs
  become_user: vagrant
  ignore_errors: true


