---
- name: Get Nomad binary archieve
  get_url:
    url: https://releases.hashicorp.com/nomad/{{ nomad_version }}/{{ nomad_version }}_linux_amd64.zip
    dest: /tmp//{{ nomad_version }}_linux_amd64.zip
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 3
  check_mode: false

- name: Unpack nomad binary
  unarchive:
    src: /tmp//{{ nomad_version }}_linux_amd64.zip
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/nomad"
    remote_src: yes
  check_mode: false

- name: Create needed folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/nomad.d
    - /opt/nomad

- name: Template a nomad.hcl
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: Template a server.hcl
  template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: Template a nomad.service
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
  notify:
    - Restart nomad

